[mcp_servers.context7]
args = [
    "/c",
    "npx",
    "-y",
    "@upstash/context7-mcp",
]
command = "cmd"

[mcp_servers.filesystem]
args = [
    "/c",
    "npx",
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "C:/Users/camil/Downloads/cermont_aplicativo/cermont_aplicativo",
]
command = "cmd"

[mcp_servers.gemini-api-docs-mcp]
type = "http"
url = "https://gemini-api-docs-mcp.dev"

[mcp_servers.github]
args = [
    "/c",
    "npx",
    "-y",
    "@modelcontextprotocol/server-github",
]
command = "cmd"
env_vars = ["GITHUB_TOKEN"]

[mcp_servers.next-devtools]
args = [
    "/c",
    "npx",
    "-y",
    "next-devtools-mcp@latest",
]
command = "cmd"

[mcp_servers.playwright]
args = [
    "/c",
    "npx",
    "-y",
    "@playwright/mcp",
]
command = "cmd"

[mcp_servers.puppeteer]
args = [
    "/c",
    "npx",
    "-y",
    "@modelcontextprotocol/server-puppeteer",
]
command = "cmd"

[mcp_servers.sequential-thinking]
args = [
    "/c",
    "npx",
    "-y",
    "@modelcontextprotocol/server-sequential-thinking",
]
command = "cmd"

[mcp_servers.superpowers]
args = [
    "/c",
    "npx",
    "-y",
    "@upstash/mcp-server-superpowers",
]
command = "cmd"

[shell_environment_policy]
inherit = "core"

[shell_environment_policy.set]
ANTHROPIC_BASE_URL = "http://localhost:11434"
API_TIMEOUT_MS = "3000000"
