/**
 * Centralized Error Codes Registry
 *
 * Single source of truth for all error codes used across the backend.
 * Prevents magic strings and ensures consistency across all modules.
 *
 * Usage:
 *   throw new AppError('Order not found', 404, ERROR_CODES.NOT_FOUND)
 */

export const ERROR_CODES = {
	// Generic
	INTERNAL_ERROR: "INTERNAL_ERROR",
	BAD_REQUEST: "BAD_REQUEST",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	NOT_FOUND: "NOT_FOUND",
	UNAUTHORIZED: "UNAUTHORIZED",
	FORBIDDEN: "FORBIDDEN",
	CONFLICT: "CONFLICT",
	RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
	BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",

	// Auth
	INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
	TOKEN_EXPIRED: "TOKEN_EXPIRED",
	TOKEN_INVALID: "TOKEN_INVALID",
	ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
	EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",

	// Orders
	ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
	INVALID_STATUS: "INVALID_STATUS",
	INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
	ORDER_ALREADY_CLOSED: "ORDER_ALREADY_CLOSED",

	// Users
	USER_NOT_FOUND: "USER_NOT_FOUND",
	INVALID_PASSWORD: "INVALID_PASSWORD",
	CANNOT_DELETE_SELF: "CANNOT_DELETE_SELF",

	// Files
	FILE_TOO_LARGE: "FILE_TOO_LARGE",
	INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
	FILE_NOT_FOUND: "FILE_NOT_FOUND",
	UPLOAD_FAILED: "UPLOAD_FAILED",

	// Resources
	RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
	INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

	// Reports
	REPORT_GENERATION_FAILED: "REPORT_GENERATION_FAILED",
	REPORT_NOT_FOUND: "REPORT_NOT_FOUND",

	// Costs
	COST_NOT_FOUND: "COST_NOT_FOUND",
	BUDGET_EXCEEDED: "BUDGET_EXCEEDED",

	// Maintenance
	MAINTENANCE_NOT_FOUND: "MAINTENANCE_NOT_FOUND",
	MAINTENANCE_ALREADY_SCHEDULED: "MAINTENANCE_ALREADY_SCHEDULED",

	// Inspections
	INSPECTION_NOT_FOUND: "INSPECTION_NOT_FOUND",
	INSPECTION_FAILED: "INSPECTION_FAILED",

	// Evidences
	EVIDENCE_NOT_FOUND: "EVIDENCE_NOT_FOUND",

	// Proposals
	PROPOSAL_NOT_FOUND: "PROPOSAL_NOT_FOUND",
	PROPOSAL_ALREADY_APPROVED: "PROPOSAL_ALREADY_APPROVED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
