import fs from "node:fs";
import path from "node:path";
import { expect, test } from "@playwright/test";

const backendUrl = process.env.BACKEND_URL ?? "http://localhost:4000";
const authDir = path.join(process.cwd(), "tests/e2e/fixtures/.auth");
const adminStorageState = path.join(authDir, "admin.json");
const seedFile = path.join(authDir, "seed-data.json");
const sourceImagePath = path.join(
	process.cwd(),
	"public/images/optimized/login/chatgpt-image-25-may-2026-23-14-19-3-640.webp",
);

interface SeedData {
	admin: {
		accessToken?: string;
	};
}

interface ResourceCreateResponse {
	success: boolean;
	data: {
		_id: string;
		name: string;
		type: string;
	};
}

interface FileListResponse {
	success: boolean;
	data: Array<{
		id: string;
		originalName: string;
		storedName: string;
		url: string;
		entityType: string;
		entityId: string;
		category: string;
		syncStatus: string;
	}>;
}

function readAdminAccessToken(): string {
	const seed = JSON.parse(fs.readFileSync(seedFile, "utf8")) as SeedData;
	const token = seed.admin.accessToken;
	if (!token) {
		throw new Error("E2E admin access token was not generated by global setup");
	}
	return token;
}

test.describe("real file upload", () => {
	test.use({ storageState: adminStorageState });

	test("uploads a real resource image, persists metadata, and renders after reload", async ({
		page,
		request,
	}) => {
		const accessToken = readAdminAccessToken();
		const resourceName = `E2E File Upload Tool ${Date.now()}`;
		const createResourceResponse = await request.post(`${backendUrl}/api/resources`, {
			headers: { Authorization: `Bearer ${accessToken}` },
			data: {
				name: resourceName,
				type: "tool",
				description: "E2E owner for real file upload proof",
			},
		});
		expect(createResourceResponse.status()).toBe(201);
		const resourceBody = (await createResourceResponse.json()) as ResourceCreateResponse;
		expect(resourceBody.success).toBe(true);

		await page.goto(`/resources/${resourceBody.data._id}`);
		await expect(page.getByRole("heading", { name: resourceName })).toBeVisible();
		await expect(page.getByRole("heading", { name: "Archivos del recurso" })).toBeVisible();

		const uploadResponsePromise = page.waitForResponse(
			(response) =>
				response.url().includes("/api/backend/files/upload") &&
				response.request().method() === "POST",
		);

		const imageBuffer = fs.readFileSync(sourceImagePath);
		await page.locator("input[type='file'][aria-label='Subir foto']").setInputFiles({
			name: "e2e-resource-photo.webp",
			mimeType: "image/webp",
			buffer: imageBuffer,
		});

		const uploadResponse = await uploadResponsePromise;
		expect(uploadResponse.status()).toBe(201);
		await expect(page.getByText("e2e-resource-photo.jpg").first()).toBeVisible();

		await page.reload();
		await expect(page.getByText("e2e-resource-photo.jpg").first()).toBeVisible();

		const image = page.locator("img[alt='e2e-resource-photo.jpg']").first();
		await expect(image).toBeVisible();
		await expect
			.poll(async () => image.evaluate((node) => (node as HTMLImageElement).naturalWidth))
			.toBeGreaterThan(0);
		const imageSrc = await image.getAttribute("src");
		expect(imageSrc).toContain("/uploads/");
		const storedImageResponse = await page.request.get(imageSrc ?? "");
		expect(storedImageResponse.status()).toBe(200);

		const filesResponse = await request.get(
			`${backendUrl}/api/files?entityType=tool&entityId=${resourceBody.data._id}`,
			{ headers: { Authorization: `Bearer ${accessToken}` } },
		);
		expect(filesResponse.status()).toBe(200);
		const filesBody = (await filesResponse.json()) as FileListResponse;
		expect(filesBody.success).toBe(true);
		expect(filesBody.data).toEqual(
			expect.arrayContaining([
				expect.objectContaining({
					originalName: "e2e-resource-photo.jpg",
					entityType: "tool",
					entityId: resourceBody.data._id,
					category: "tool_image",
					syncStatus: "synced",
				}),
			]),
		);
	});
});
