/**
 * API Docs — OpenAPI 3 document generated by Express router introspection.
 *
 * Avoids swagger-jsdoc/swagger-ui-express dependencies (policy: no large
 * dependencies without justification). The document is built once at boot
 * from the real mounted routers, so it can never list endpoints that do
 * not exist.
 */

import type { Router } from "express";

interface RouteLayer {
	route?: {
		path: string;
		methods: Record<string, boolean>;
	};
}

export interface ApiMount {
	prefix: string;
	router: Router;
}

interface OpenApiOperation {
	tags: string[];
	summary: string;
	security: Array<Record<string, string[]>>;
	responses: Record<string, { description: string }>;
}

type OpenApiPaths = Record<string, Record<string, OpenApiOperation>>;

function toOpenApiPath(prefix: string, routePath: string): string {
	const joined = `${prefix}${routePath === "/" ? "" : routePath}`;
	return joined.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

function tagFromPrefix(prefix: string): string {
	return prefix.replace(/^\/api\//, "");
}

function buildOperation(prefix: string, method: string, fullPath: string): OpenApiOperation {
	return {
		tags: [tagFromPrefix(prefix)],
		summary: `${method.toUpperCase()} ${fullPath}`,
		security: [{ bearerAuth: [] }],
		responses: {
			"200": { description: "Success — { success: true, data }" },
			"400": { description: "Validation error — { success: false, error }" },
			"401": { description: "Not authenticated" },
			"403": { description: "Forbidden (RBAC)" },
		},
	};
}

function collectRoutePaths(paths: OpenApiPaths, prefix: string, layer: RouteLayer): void {
	if (!layer.route) {
		return;
	}
	const fullPath = toOpenApiPath(prefix, layer.route.path);
	const pathEntry = paths[fullPath] ?? {};
	for (const [method, enabled] of Object.entries(layer.route.methods)) {
		if (enabled && method !== "_all") {
			pathEntry[method] = buildOperation(prefix, method, fullPath);
		}
	}
	paths[fullPath] = pathEntry;
}

export function buildOpenApiDocument(mounts: ApiMount[], version: string) {
	const paths: OpenApiPaths = {};

	for (const { prefix, router } of mounts) {
		const stack = (router as unknown as { stack?: RouteLayer[] }).stack ?? [];
		for (const layer of stack) {
			collectRoutePaths(paths, prefix, layer);
		}
	}

	return {
		openapi: "3.0.3",
		info: {
			title: "CERMONT API",
			description:
				"API del aplicativo CERMONT S.A.S. — gestión de órdenes de trabajo, " +
				"trazabilidad y cierre administrativo. Todas las rutas usan el envelope " +
				"{ success, data | error } y requieren JWT salvo /api/auth y /api/health.",
			version,
		},
		servers: [{ url: "/", description: "Servidor actual" }],
		components: {
			securitySchemes: {
				bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
			},
		},
		paths,
	};
}

export function buildDocsHtml(): string {
	return `<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>CERMONT API Docs</title>
<style>
body{font-family:system-ui,sans-serif;margin:0;background:#0f1729;color:#e2e8f0}
header{padding:24px 32px;border-bottom:1px solid #1e293b}
h1{margin:0;font-size:20px}
p{color:#94a3b8;font-size:14px}
main{padding:16px 32px 48px}
.tag{margin-top:28px;font-size:15px;font-weight:600;color:#7dd3fc;text-transform:capitalize}
.route{display:flex;gap:12px;align-items:center;padding:7px 12px;margin-top:6px;background:#1e293b;border-radius:8px;font-family:ui-monospace,monospace;font-size:13px}
.m{min-width:58px;text-align:center;border-radius:6px;padding:2px 0;font-weight:700;font-size:11px}
.get{background:#0e4429;color:#4ade80}.post{background:#1e3a8a;color:#93c5fd}
.put{background:#713f12;color:#fbbf24}.patch{background:#713f12;color:#fbbf24}
.delete{background:#7f1d1d;color:#fca5a5}
</style>
</head>
<body>
<header>
<h1>CERMONT API</h1>
<p>Documentación generada desde los routers reales. JSON: <a style="color:#7dd3fc" href="/api/docs/openapi.json">/api/docs/openapi.json</a></p>
</header>
<main id="routes">Cargando…</main>
<script>
fetch("/api/docs/openapi.json").then(function(r){return r.json()}).then(function(doc){
	var byTag = {};
	Object.keys(doc.paths).sort().forEach(function(p){
		Object.keys(doc.paths[p]).forEach(function(m){
			var tag = doc.paths[p][m].tags[0] || "otros";
			(byTag[tag] = byTag[tag] || []).push({ method: m, path: p });
		});
	});
	var html = "";
	Object.keys(byTag).sort().forEach(function(tag){
		html += '<div class="tag">' + tag + "</div>";
		byTag[tag].forEach(function(r){
			html += '<div class="route"><span class="m ' + r.method + '">' +
				r.method.toUpperCase() + "</span><span>" + r.path + "</span></div>";
		});
	});
	document.getElementById("routes").innerHTML = html;
});
</script>
</body>
</html>`;
}
