import { z } from "zod";
import { UserRoleSchema } from "./user.schema";

export const CermontOperationalStepCodeSchema = z.enum([
	"step_01_work_request",
	"step_02_site_visit",
	"step_03_proposal",
	"step_04_purchase_order",
	"step_05_planning",
	"step_06_execution",
	"step_07_technical_report",
	"step_08_delivery_record",
	"step_09_client_signature",
	"step_10_ses_submission",
	"step_11_ses_approval",
	"step_12_invoice_submission",
	"step_13_invoice_approval",
	"step_14_payment_closure",
]);

export type CermontOperationalStepCode = z.infer<typeof CermontOperationalStepCodeSchema>;

export const CermontOperationalStepViewSchema = z.object({
	stepNumber: z.number().min(1).max(14),
	code: CermontOperationalStepCodeSchema,
	label: z.string(),
	description: z.string(),
	phase: z.enum(["operational", "administrative"]),
	entityType: z.string(),
	relatedEntity: z.string(),
	route: z.string(),
	allowedRoles: z.array(UserRoleSchema),
	requiredDocuments: z.array(z.string()),
	requiredEvidences: z.array(z.string()),
	requiredSignatures: z.array(z.string()),
	requiredForms: z.array(z.string()),
	blocksTransition: z.boolean(),
	nextAction: z.string(),
});

export type CermontOperationalStepView = z.infer<typeof CermontOperationalStepViewSchema>;

export const CERMONT_OPERATIONAL_STEPS = [
	{
		stepNumber: 1,
		code: "step_01_work_request",
		label: "Solicitud de servicio",
		description: "Registrar y validar la necesidad del cliente antes de iniciar cualquier gestión.",
		phase: "operational",
		entityType: "workRequest",
		relatedEntity: "work_request",
		route: "/service-cases/[id]/work-request",
		allowedRoles: ["gerente", "residente", "administrativo", "cliente"],
		requiredDocuments: ["work_request"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Registrar o validar solicitud de servicio",
	},
	{
		stepNumber: 2,
		code: "step_02_site_visit",
		label: "Visita técnica",
		description:
			"Levantar condiciones reales de sitio y soportar técnicamente la solución propuesta.",
		phase: "operational",
		entityType: "siteVisit",
		relatedEntity: "site_visit",
		route: "/service-cases/[id]/site-visit",
		allowedRoles: ["residente", "supervisor", "gerente"],
		requiredDocuments: ["site_visit_report"],
		requiredEvidences: ["before_photos"],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Registrar visita técnica e inspeccionar sitio",
	},
	{
		stepNumber: 3,
		code: "step_03_proposal",
		label: "Propuesta económica",
		description:
			"Formalizar alcance, cantidades y condiciones comerciales para aprobación del cliente.",
		phase: "operational",
		entityType: "proposal",
		relatedEntity: "proposal",
		route: "/service-cases/[id]/proposal",
		allowedRoles: ["gerente", "residente", "administrativo"],
		requiredDocuments: ["proposal_document"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Elaborar propuesta comercial e indicar tarifas",
	},
	{
		stepNumber: 4,
		code: "step_04_purchase_order",
		label: "Aprobación / Orden de compra",
		description: "Asegurar la autorización contractual antes de comprometer recursos operativos.",
		phase: "operational",
		entityType: "purchaseOrder",
		relatedEntity: "purchase_order",
		route: "/service-cases/[id]/purchase-order",
		allowedRoles: ["gerente", "administrativo", "cliente"],
		requiredDocuments: ["purchase_order"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Subir orden de compra firmada y validar aprobación",
	},
	{
		stepNumber: 5,
		code: "step_05_planning",
		label: "Planeación de recursos",
		description:
			"Asignar cuadrilla, herramientas, seguridad y cronograma para ejecutar el servicio.",
		phase: "operational",
		entityType: "planningPacket",
		relatedEntity: "planning_packet",
		route: "/service-cases/[id]/planning",
		allowedRoles: ["gerente", "residente", "supervisor"],
		requiredDocuments: ["planning_packet"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Asignar cuadrilla, herramientas y cronograma",
	},
	{
		stepNumber: 6,
		code: "step_06_execution",
		label: "Ejecución en campo",
		description:
			"Registrar la ejecución real, consumos, incidentes, evidencias y firmas operativas.",
		phase: "operational",
		entityType: "executionSession",
		relatedEntity: "execution_session",
		route: "/service-cases/[id]/execution",
		allowedRoles: ["residente", "supervisor", "operador", "tecnico"],
		requiredDocuments: ["ast_document", "ptw_document"],
		requiredEvidences: ["during_photos"],
		requiredSignatures: ["firma_tecnico", "firma_supervisor"],
		requiredForms: ["execution_checklist", "execution_dynamic_form"],
		blocksTransition: true,
		nextAction: "Diligenciar AST, permisos y registrar labor",
	},
	{
		stepNumber: 7,
		code: "step_07_technical_report",
		label: "Informe técnico",
		description: "Consolidar resultados técnicos y cierre operacional del trabajo ejecutado.",
		phase: "operational",
		entityType: "technicalReport",
		relatedEntity: "technical_report",
		route: "/service-cases/[id]/technical-report",
		allowedRoles: ["residente", "supervisor", "tecnico"],
		requiredDocuments: ["technical_report"],
		requiredEvidences: ["after_photos"],
		requiredSignatures: [],
		requiredForms: ["technical_report_form"],
		blocksTransition: true,
		nextAction: "Registrar informe técnico final y soportes de obra",
	},
	{
		stepNumber: 8,
		code: "step_08_delivery_record",
		label: "Acta de entrega",
		description: "Generar el acta que formaliza la entrega técnica y operativa del servicio.",
		phase: "administrative",
		entityType: "deliveryRecord",
		relatedEntity: "delivery_record",
		route: "/service-cases/[id]/delivery-record",
		allowedRoles: ["residente", "supervisor", "administrativo", "gerente"],
		requiredDocuments: ["delivery_record"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Generar acta de entrega física y técnica",
	},
	{
		stepNumber: 9,
		code: "step_09_client_signature",
		label: "Firma del cliente",
		description: "Obtener aceptación expresa del cliente sobre la entrega realizada.",
		phase: "administrative",
		entityType: "clientSignature",
		relatedEntity: "delivery_record_signature",
		route: "/service-cases/[id]/client-signature",
		allowedRoles: ["gerente", "residente", "cliente"],
		requiredDocuments: ["signed_delivery_record"],
		requiredEvidences: [],
		requiredSignatures: ["client_signature"],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Obtener firma del cliente en el acta",
	},
	{
		stepNumber: 10,
		code: "step_10_ses_submission",
		label: "Radicación SES",
		description: "Radicar la SES o soporte equivalente en el sistema del cliente.",
		phase: "administrative",
		entityType: "serviceEntrySheet",
		relatedEntity: "service_entry_sheet",
		route: "/service-cases/[id]/ses",
		allowedRoles: ["administrativo", "gerente"],
		requiredDocuments: ["ses_receipt"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Radicar hoja de entrada de servicio (SES / Ariba)",
	},
	{
		stepNumber: 11,
		code: "step_11_ses_approval",
		label: "Aprobación SES",
		description: "Confirmar que la SES fue aceptada y aprobada por el cliente.",
		phase: "administrative",
		entityType: "serviceEntrySheetApproval",
		relatedEntity: "service_entry_sheet_approval",
		route: "/service-cases/[id]/ses",
		allowedRoles: ["gerente", "administrativo"],
		requiredDocuments: ["ses_approval_document"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Validar aprobación y número de SES en sistema del cliente",
	},
	{
		stepNumber: 12,
		code: "step_12_invoice_submission",
		label: "Emisión / envío de factura",
		description: "Emitir la factura y enviarla formalmente con sus soportes de cobro.",
		phase: "administrative",
		entityType: "invoice",
		relatedEntity: "invoice",
		route: "/service-cases/[id]/invoice",
		allowedRoles: ["administrativo", "gerente"],
		requiredDocuments: ["invoice_document"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Emitir y enviar factura electrónica de venta",
	},
	{
		stepNumber: 13,
		code: "step_13_invoice_approval",
		label: "Aprobación de factura",
		description: "Validar que la factura fue aceptada para entrar al ciclo de pago.",
		phase: "administrative",
		entityType: "invoiceApproval",
		relatedEntity: "invoice_approval",
		route: "/service-cases/[id]/invoice",
		allowedRoles: ["gerente", "administrativo"],
		requiredDocuments: ["invoice_approval_document"],
		requiredEvidences: [],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Verificar aprobación de la factura para pago",
	},
	{
		stepNumber: 14,
		code: "step_14_payment_closure",
		label: "Pago y cierre definitivo",
		description:
			"Registrar pago, conciliación bancaria y cierre administrativo definitivo del caso.",
		phase: "administrative",
		entityType: "payment",
		relatedEntity: "payment",
		route: "/service-cases/[id]/payment",
		allowedRoles: ["gerente", "administrativo"],
		requiredDocuments: ["payment_voucher"],
		requiredEvidences: ["bank_statement"],
		requiredSignatures: [],
		requiredForms: [],
		blocksTransition: true,
		nextAction: "Registrar pago, conciliar costos y cerrar orden",
	},
] as const satisfies readonly CermontOperationalStepView[];
