"use client";

import { APPROVER_ROLES, hasRole } from "@cermont/shared-types/rbac";
import { CheckCircle2, FileWarning, RefreshCw, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useAuthStore } from "@/_shared/store/auth.store";
import { useOrder } from "@/orders/queries";
import {
	ReportDownloadButton,
	ReportStatusBadge,
	useApproveReport,
	useOrderReport,
	useRejectReport,
	useSyncReport,
	useUpdateReport,
} from "..";

interface ReportPanelProps {
	orderId: string;
	readOnly?: boolean;
}

export function ReportPanel({ orderId, readOnly = false }: ReportPanelProps) {
	const { data: order, isLoading: orderLoading, error: orderError } = useOrder(orderId);
	const { data: report, isLoading: reportLoading, error: reportError } = useOrderReport(orderId);
	const currentRole = useAuthStore((state) => state.user?.role);
	const updateReport = useUpdateReport(report?._id ?? "");
	const approveReport = useApproveReport(report?._id ?? "");
	const rejectReport = useRejectReport(report?._id ?? "");
	const syncReport = useSyncReport(orderId);
	const [rejectionReason, setRejectionReason] = useState("");

	const canReview = hasRole(currentRole ?? "", APPROVER_ROLES);

	const handleApprove = async () => {
		if (!report) {
			return;
		}

		try {
			await approveReport.mutateAsync();
			toast.success("Informe aprobado");
		} catch (error) {
			toast.error(error instanceof Error ? error.message : "No se pudo aprobar el informe");
		}
	};

	const handleReject = async () => {
		if (!report) {
			return;
		}

		try {
			await rejectReport.mutateAsync(rejectionReason.trim() || "Rechazado para ajustes");
			toast.success("Informe rechazado");
		} catch (error) {
			toast.error(error instanceof Error ? error.message : "No se pudo rechazar el informe");
		}
	};

	const handleRegenerate = async () => {
		if (!report) {
			return;
		}

		try {
			await updateReport.mutateAsync({ status: "draft", rejectionReason: "" });
			toast.success("Informe regresado a borrador");
		} catch (error) {
			toast.error(error instanceof Error ? error.message : "No se pudo regenerar el informe");
		}
	};

	const handleSync = async () => {
		try {
			await syncReport.mutateAsync();
			toast.success("Informe sincronizado con los datos más recientes");
		} catch (error) {
			toast.error(error instanceof Error ? error.message : "No se pudo sincronizar el informe");
		}
	};

	if (orderLoading || reportLoading) {
		return <ReportSkeleton />;
	}

	if (orderError || reportError) {
		return (
			<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700 dark:border-red-900/30 dark:bg-red-900/10 dark:text-red-300">
				No se pudo cargar el informe.
			</div>
		);
	}

	const actionPending =
		updateReport.isPending ||
		approveReport.isPending ||
		rejectReport.isPending ||
		syncReport.isPending;
	const isAutoGeneratedDraft =
		Boolean(report) &&
		report?.status === "draft" &&
		Boolean(order) &&
		["completed", "ready_for_invoicing", "closed"].includes(order?.status ?? "");

	return (
		<section
			aria-labelledby="work-report-title"
			className="space-y-4 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950 sm:p-6"
		>
			<div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
				<div className="space-y-2">
					<div className="flex flex-wrap items-center gap-2">
						<h2
							id="work-report-title"
							className="text-lg font-semibold text-slate-950 dark:text-white"
						>
							Informe de trabajo
						</h2>
						{report ? (
							<ReportStatusBadge status={report.status} />
						) : (
							<span className="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-medium text-slate-700 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">
								Sin informe
							</span>
						)}
					</div>
					<p className="text-sm text-slate-600 dark:text-slate-400">
						Consolida checklist firmado, costos, evidencias y la aprobación operativa antes de
						facturar.
					</p>
				</div>
			</div>

			{report ? (
				<div className="space-y-4">
					{report.status === "draft" ? (
						<aside
							role="status"
							className="flex flex-col gap-3 rounded-lg border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900 dark:border-blue-900/30 dark:bg-blue-900/10 dark:text-blue-300 sm:flex-row sm:items-center sm:justify-between"
						>
							<p>
								{isAutoGeneratedDraft
									? "Borrador auto-generado con datos de la orden."
									: "Borrador del informe listo para revisión."}
							</p>
							<button
								type="button"
								onClick={handleSync}
								disabled={syncReport.isPending}
								className="inline-flex min-h-11 items-center justify-center rounded-lg border border-blue-300 bg-white px-3 py-2 text-sm font-medium text-blue-900 transition-colors hover:bg-blue-100 disabled:cursor-not-allowed disabled:opacity-60 dark:border-blue-800 dark:bg-slate-950 dark:text-blue-300 dark:hover:bg-slate-900"
							>
								{syncReport.isPending ? "Sincronizando..." : "Sincronizar datos"}
							</button>
						</aside>
					) : null}

					<div className="grid gap-3 sm:grid-cols-3">
						<InfoCard
							label="Checklist"
							value={report.includesChecklist ? "Incluido" : "No incluido"}
							tone={report.includesChecklist ? "green" : "slate"}
						/>
						<InfoCard
							label="Costos"
							value={report.includesCosts ? "Incluidos" : "No incluidos"}
							tone={report.includesCosts ? "green" : "slate"}
						/>
						<InfoCard
							label="Evidencias"
							value={report.includesEvidences ? "Incluidas" : "No incluidas"}
							tone={report.includesEvidences ? "green" : "slate"}
						/>
					</div>

					<div className="rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900">
						<p className="text-xs font-medium uppercase tracking-wide text-slate-500 dark:text-slate-400">
							Resumen
						</p>
						<p className="mt-2 text-sm leading-relaxed text-slate-700 dark:text-slate-300">
							{report.summary}
						</p>
					</div>

					{report.status === "draft" && !readOnly ? (
						<div className="space-y-3 rounded-lg border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900">
							{canReview ? (
								<div className="flex flex-col gap-3 sm:flex-row sm:items-center">
									<button
										type="button"
										onClick={handleApprove}
										disabled={actionPending}
										aria-label="Aprobar informe"
										className="min-h-11 inline-flex items-center justify-center gap-2 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-green-700 disabled:cursor-not-allowed disabled:opacity-60 dark:bg-green-500 dark:hover:bg-green-600"
									>
										<CheckCircle2 className="h-4 w-4" aria-hidden="true" />
										Aprobar informe
									</button>
									<div className="flex flex-1 flex-col gap-2 sm:flex-row">
										<input
											value={rejectionReason}
											onChange={(event) => setRejectionReason(event.target.value)}
											placeholder="Motivo de rechazo"
											aria-label="Motivo de rechazo"
											className="min-h-11 min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-900 outline-none transition focus:border-blue-500 dark:border-slate-700 dark:bg-slate-950 dark:text-white"
										/>
										<button
											type="button"
											onClick={handleReject}
											disabled={actionPending}
											className="min-h-11 inline-flex items-center justify-center gap-2 rounded-lg border border-red-200 bg-red-50 px-4 py-2 text-sm font-medium text-red-900 transition-colors hover:bg-red-100 disabled:cursor-not-allowed disabled:opacity-60 dark:border-red-900/30 dark:bg-red-900/10 dark:text-red-300"
										>
											<ShieldAlert className="h-4 w-4" aria-hidden="true" />
											Rechazar
										</button>
									</div>
								</div>
							) : (
								<p className="text-sm text-slate-500 dark:text-slate-400">
									El borrador ya está listo. Queda pendiente aprobación por supervisor o gerente.
								</p>
							)}
						</div>
					) : null}

					{report.status === "approved" && (
						<div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
							<p className="text-sm text-green-700 dark:text-green-300">
								El informe fue aprobado y ya puede descargarse.
							</p>
							<ReportDownloadButton orderId={orderId} />
						</div>
					)}

					{report.status === "rejected" && !readOnly && (
						<div className="space-y-3 rounded-lg border border-red-200 bg-red-50 p-4 dark:border-red-900/30 dark:bg-red-900/10">
							<div className="flex items-start gap-2 text-sm text-red-900 dark:text-red-300">
								<FileWarning className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
								<p>
									{report.rejectionReason ||
										"El informe fue rechazado y requiere ajustes antes de reenviarlo."}
								</p>
							</div>
							<button
								type="button"
								onClick={handleRegenerate}
								disabled={actionPending}
								className="inline-flex items-center justify-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-medium text-slate-900 ring-1 ring-inset ring-slate-300 transition-colors hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60 dark:bg-slate-950 dark:text-white dark:ring-slate-700 dark:hover:bg-slate-900"
							>
								<RefreshCw className="h-4 w-4" aria-hidden="true" />
								Regenerar
							</button>
						</div>
					)}
				</div>
			) : (
				<div className="flex items-start gap-3 rounded-lg border border-dashed border-slate-300 bg-slate-50 p-4 text-sm text-slate-600 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-400">
					<FileWarning className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
					<p>
						{order?.status === "completed"
							? "El borrador del informe se está preparando automáticamente."
							: "El informe aparecerá automáticamente cuando la orden complete la ejecución."}
					</p>
				</div>
			)}
		</section>
	);
}

function InfoCard({
	label,
	value,
	tone,
}: {
	label: string;
	value: string;
	tone: "green" | "slate";
}) {
	return (
		<article
			className={`rounded-lg border p-3 ${tone === "green" ? "border-green-200 bg-green-50 dark:border-green-900/30 dark:bg-green-900/10" : "border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-slate-900"}`}
		>
			<p
				className={`text-xs font-medium uppercase tracking-wide ${tone === "green" ? "text-green-700 dark:text-green-300" : "text-slate-500 dark:text-slate-400"}`}
			>
				{label}
			</p>
			<p
				className={`mt-1 text-sm font-medium ${tone === "green" ? "text-green-900 dark:text-green-300" : "text-slate-900 dark:text-white"}`}
			>
				{value}
			</p>
		</article>
	);
}

function ReportSkeleton() {
	const kpiKeys = Array.from({ length: 3 }, (_, i) => `report-kpi-sk-${i}`);

	return (
		<div className="animate-pulse space-y-4 rounded-xl border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-950 sm:p-6">
			<div className="h-6 w-48 rounded bg-slate-200 dark:bg-slate-800" />
			<div className="h-4 w-80 rounded bg-slate-200 dark:bg-slate-800" />
			<div className="grid gap-3 sm:grid-cols-3">
				{kpiKeys.map((k) => (
					<div key={k} className="h-16 rounded-lg bg-slate-200 dark:bg-slate-800" />
				))}
			</div>
			<div className="h-24 rounded-lg bg-slate-200 dark:bg-slate-800" />
		</div>
	);
}
