export const AUTH_CONSTANTS = {
  JWT_SECRET_ENV: 'JWT_SECRET',
  JWT_EXPIRES_IN_ENV: 'JWT_EXPIRES_IN',
  JWT_DEFAULT_EXPIRES_IN: '15m',

  // Refresh tokens
  REFRESH_TOKEN_DAYS_DEFAULT: 7,
  REFRESH_TOKEN_DAYS_REMEMBER: 30,

  // Cache
  JWT_USER_CACHE_TTL_MS_ENV: 'JWT_USER_CACHE_TTL_MS',
  JWT_USER_CACHE_TTL_MS_DEFAULT: 30_000,
  JWT_USER_CACHE_KEY_PREFIX: 'auth:jwt:user:',
} as const;
