/**
 * Audit Log Actions — Single Source of Truth
 */

export const AUDIT_ACTIONS = {
	// Template Management
	TEMPLATE_CREATED: "TEMPLATE_CREATED",
	TEMPLATE_UPDATED: "TEMPLATE_UPDATED",
	TEMPLATE_CLASSIFIED: "TEMPLATE_CLASSIFIED",
	TEMPLATE_DELETED: "TEMPLATE_DELETED",

	// Template Versions
	VERSION_CREATED: "VERSION_CREATED",
	VERSION_UPDATED: "VERSION_UPDATED",
	VERSION_PUBLISHED: "VERSION_PUBLISHED",
	VERSION_DEPRECATED: "VERSION_DEPRECATED",
	VERSION_CLONED: "VERSION_CLONED",

	// Form Responses
	RESPONSE_CREATED: "RESPONSE_CREATED",
	RESPONSE_UPDATED: "RESPONSE_UPDATED",
	RESPONSE_SUBMITTED: "RESPONSE_SUBMITTED",
	RESPONSE_VALIDATED: "RESPONSE_VALIDATED",
	RESPONSE_REJECTED: "RESPONSE_REJECTED",
	RESPONSE_SYNCED: "RESPONSE_SYNCED",

	// Files & Imports
	FILE_UPLOADED: "FILE_UPLOADED",
	FILE_SCANNED: "FILE_SCANNED",
	XLSX_IMPORT_STARTED: "XLSX_IMPORT_STARTED",
	PDF_IMPORT_STARTED: "PDF_IMPORT_STARTED",

	// Asset & Maintenance
	ASSET_CREATED: "ASSET_CREATED",
	CERTIFICATE_ADDED: "CERTIFICATE_ADDED",
	MAINTENANCE_RESOLVED: "MAINTENANCE_RESOLVED",
} as const;

export type AuditAction = keyof typeof AUDIT_ACTIONS;
