/**
 * Audit Log Actions — Single Source of Truth
 *
 * Must contain EVERY action that createAuditLog can receive.
 * WORKFLOW section added per code audit gap — missing workflow actions
 * prevented proper filtering of operational audit events.
 */

export const AUDIT_ACTIONS = {
	// ── Workflow: Work Requests ──────────────────────────────────────
	WORK_REQUEST_CREATED: "WORK_REQUEST_CREATED",
	WORK_REQUEST_VALIDATED: "WORK_REQUEST_VALIDATED",
	WORK_REQUEST_CANCELLED: "WORK_REQUEST_CANCELLED",

	// ── Workflow: Site Visits ────────────────────────────────────────
	SITE_VISIT_SCHEDULED: "SITE_VISIT_SCHEDULED",
	SITE_VISIT_COMPLETED: "SITE_VISIT_COMPLETED",

	// ── Workflow: Proposals ──────────────────────────────────────────
	PROPOSAL_CREATED: "PROPOSAL_CREATED",
	PROPOSAL_APPROVED: "PROPOSAL_APPROVED",
	PROPOSAL_REJECTED: "PROPOSAL_REJECTED",

	// ── Workflow: Purchase Orders ────────────────────────────────────
	PURCHASE_ORDER_RECEIVED: "PURCHASE_ORDER_RECEIVED",
	PURCHASE_ORDER_APPROVED: "PURCHASE_ORDER_APPROVED",

	// ── Workflow: Orders ─────────────────────────────────────────────
	ORDER_CREATED: "ORDER_CREATED",
	ORDER_UPDATED: "ORDER_UPDATED",
	ORDER_ASSIGNED: "ORDER_ASSIGNED",
	ORDER_DELETED: "ORDER_DELETED",
	STATUS_CHANGED: "STATUS_CHANGED",
	ORDER_CLOSED: "ORDER_CLOSED",

	// ── Workflow: Planning ───────────────────────────────────────────
	PLANNING_PACKET_CREATED: "PLANNING_PACKET_CREATED",
	PLANNING_PACKET_UPDATED: "PLANNING_PACKET_UPDATED",
	PLANNING_PACKET_VALIDATED: "PLANNING_PACKET_VALIDATED",
	PLANNING_PACKET_APPROVED: "PLANNING_PACKET_APPROVED",
	PLANNING_PACKET_REJECTED: "PLANNING_PACKET_REJECTED",
	PLANNING_PACKET_REOPENED: "PLANNING_PACKET_REOPENED",
	REFERENCE_DOCUMENT_ADDED: "REFERENCE_DOCUMENT_ADDED",

	// ── Workflow: Execution ──────────────────────────────────────────
	EXECUTION_STARTED: "EXECUTION_STARTED",
	EXECUTION_PAUSED: "EXECUTION_PAUSED",
	EXECUTION_RESUMED: "EXECUTION_RESUMED",
	EXECUTION_COMPLETED: "EXECUTION_COMPLETED",
	EXECUTION_CANCELLED: "EXECUTION_CANCELLED",
	MATERIAL_USAGE_RECORDED: "MATERIAL_USAGE_RECORDED",
	LABOR_ENTRY_RECORDED: "LABOR_ENTRY_RECORDED",
	INCIDENT_REPORTED: "INCIDENT_REPORTED",

	// ── Workflow: Evidence ───────────────────────────────────────────
	EVIDENCE_UPLOADED: "EVIDENCE_UPLOADED",
	EVIDENCE_DELETED: "EVIDENCE_DELETED",
	EVIDENCE_VERIFIED: "EVIDENCE_VERIFIED",
	EVIDENCE_REJECTED: "EVIDENCE_REJECTED",
	EVIDENCE_REPLACED: "EVIDENCE_REPLACED",
	EVIDENCE_PDF_DOWNLOADED: "EVIDENCE_PDF_DOWNLOADED",
	EVIDENCE_FILE_VIEWED: "EVIDENCE_FILE_VIEWED",
	EVIDENCE_COLLECTION_CREATED: "EVIDENCE_COLLECTION_CREATED",
	EVIDENCE_COLLECTION_DELETED: "EVIDENCE_COLLECTION_DELETED",
	EVIDENCE_ITEM_ADDED: "EVIDENCE_ITEM_ADDED",
	EVIDENCE_ITEM_REMOVED: "EVIDENCE_ITEM_REMOVED",

	// ── Workflow: Technical Report ───────────────────────────────────
	TECHNICAL_REPORT_CREATED: "TECHNICAL_REPORT_CREATED",
	TECHNICAL_REPORT_APPROVED: "TECHNICAL_REPORT_APPROVED",

	// ── Workflow: Delivery Record ────────────────────────────────────
	DELIVERY_RECORD_CREATED: "DELIVERY_RECORD_CREATED",
	DELIVERY_RECORD_SIGNED: "DELIVERY_RECORD_SIGNED",

	// ── Workflow: SES / Ariba ────────────────────────────────────────
	SES_CREATED: "SES_CREATED",
	SES_SUBMITTED: "SES_SUBMITTED",
	SES_APPROVED: "SES_APPROVED",
	SES_REJECTED: "SES_REJECTED",

	// ── Workflow: Invoices ───────────────────────────────────────────
	INVOICE_ISSUED: "INVOICE_ISSUED",
	INVOICE_SENT: "INVOICE_SENT",
	INVOICE_APPROVED: "INVOICE_APPROVED",
	INVOICE_REJECTED: "INVOICE_REJECTED",
	INVOICE_SENT_TO_DIAN: "INVOICE_SENT_TO_DIAN",

	// ── Workflow: Payments ───────────────────────────────────────────
	PAYMENT_REGISTERED: "PAYMENT_REGISTERED",
	PAYMENT_RECONCILED: "PAYMENT_RECONCILED",

	// ── Workflow: Service Case ───────────────────────────────────────
	SERVICE_CASE_CREATED: "SERVICE_CASE_CREATED",
	SERVICE_CASE_STEP_ADVANCED: "SERVICE_CASE_STEP_ADVANCED",
	SERVICE_CASE_CLOSED: "SERVICE_CASE_CLOSED",
	SERVICE_CASE_ARCHIVED: "SERVICE_CASE_ARCHIVED",
	STEP_PAYLOAD_SUBMITTED: "STEP_PAYLOAD_SUBMITTED",
	STATE_TRANSITION: "STATE_TRANSITION",
	ARCHIVED: "ARCHIVED",

	// ── Authentication & Users ───────────────────────────────────────
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGOUT: "LOGOUT",
	REFRESH_TOKEN_REUSE_DETECTED: "REFRESH_TOKEN_REUSE_DETECTED",

	// ── Password Reset ──────────────────────────────────────────────
	PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
	PASSWORD_RESET_EMAIL_SENT: "PASSWORD_RESET_EMAIL_SENT",
	PASSWORD_RESET_EMAIL_FAILED: "PASSWORD_RESET_EMAIL_FAILED",
	PASSWORD_RESET_TOKEN_EXPIRED: "PASSWORD_RESET_TOKEN_EXPIRED",
	PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
	USER_CREATED: "USER_CREATED",
	USER_UPDATED: "USER_UPDATED",
	USER_DEACTIVATED: "USER_DEACTIVATED",
	USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
	USER_CERTIFICATION_ADDED: "USER_CERTIFICATION_ADDED",
	USER_CERTIFICATION_REMOVED: "USER_CERTIFICATION_REMOVED",
	USER_SKILLS_UPDATED: "USER_SKILLS_UPDATED",

	// ── Template Management ──────────────────────────────────────────
	TEMPLATE_CREATED: "TEMPLATE_CREATED",
	TEMPLATE_UPDATED: "TEMPLATE_UPDATED",
	TEMPLATE_CLASSIFIED: "TEMPLATE_CLASSIFIED",
	TEMPLATE_DELETED: "TEMPLATE_DELETED",

	// ── Template Versions ────────────────────────────────────────────
	VERSION_CREATED: "VERSION_CREATED",
	VERSION_UPDATED: "VERSION_UPDATED",
	VERSION_PUBLISHED: "VERSION_PUBLISHED",
	VERSION_DEPRECATED: "VERSION_DEPRECATED",
	VERSION_CLONED: "VERSION_CLONED",

	// ── Form Responses ───────────────────────────────────────────────
	RESPONSE_CREATED: "RESPONSE_CREATED",
	RESPONSE_UPDATED: "RESPONSE_UPDATED",
	RESPONSE_SUBMITTED: "RESPONSE_SUBMITTED",
	RESPONSE_VALIDATED: "RESPONSE_VALIDATED",
	RESPONSE_REJECTED: "RESPONSE_REJECTED",
	RESPONSE_SYNCED: "RESPONSE_SYNCED",

	// ── Files & Imports ──────────────────────────────────────────────
	FILE_UPLOADED: "FILE_UPLOADED",
	FILE_SCANNED: "FILE_SCANNED",
	FILE_ASSET_UPLOADED: "FILE_ASSET_UPLOADED",
	FILE_ASSET_DOWNLOADED: "FILE_ASSET_DOWNLOADED",
	FILE_ASSET_DELETED: "FILE_ASSET_DELETED",
	DOCUMENT_ARCHIVED: "DOCUMENT_ARCHIVED",
	DOCUMENT_DELETED: "DOCUMENT_DELETED",
	XLSX_IMPORT_STARTED: "XLSX_IMPORT_STARTED",
	PDF_IMPORT_STARTED: "PDF_IMPORT_STARTED",

	// ── Asset & Maintenance ──────────────────────────────────────────
	ASSET_CREATED: "ASSET_CREATED",
	ASSET_PHOTO_UPLOADED: "ASSET_PHOTO_UPLOADED",
	ASSET_PRIMARY_PHOTO_CHANGED: "ASSET_PRIMARY_PHOTO_CHANGED",
	ASSET_DOCUMENT_UPLOADED: "ASSET_DOCUMENT_UPLOADED",
	VEHICLE_CHECKED_IN: "VEHICLE_CHECKED_IN",
	VEHICLE_CHECKED_OUT: "VEHICLE_CHECKED_OUT",
	VEHICLE_ASSIGNED: "VEHICLE_ASSIGNED",
	VEHICLE_DOCUMENT_EXPIRED: "VEHICLE_DOCUMENT_EXPIRED",

	CERTIFICATE_ADDED: "CERTIFICATE_ADDED",
	MAINTENANCE_RESOLVED: "MAINTENANCE_RESOLVED",

	// ── Tools & Planning Kits ────────────────────────────────────────
	TOOL_CREATED: "TOOL_CREATED",
	TOOL_UPDATED: "TOOL_UPDATED",
	TOOL_DELETED: "TOOL_DELETED",
	TOOL_CERTIFICATION_ADDED: "TOOL_CERTIFICATION_ADDED",
	TOOL_CERTIFICATION_REMOVED: "TOOL_CERTIFICATION_REMOVED",
	TOOL_DOCUMENT_ADDED: "TOOL_DOCUMENT_ADDED",
	TOOL_DOCUMENT_REMOVED: "TOOL_DOCUMENT_REMOVED",
	KIT_CREATED: "KIT_CREATED",
	KIT_UPDATED: "KIT_UPDATED",
	KIT_ACTIVATED: "KIT_ACTIVATED",
	KIT_ARCHIVED: "KIT_ARCHIVED",
	KIT_RESTORED: "KIT_RESTORED",
	KIT_DELETED: "KIT_DELETED",
	KIT_DUPLICATED: "KIT_DUPLICATED",
	KIT_APPLIED_TO_PLANNING: "KIT_APPLIED_TO_PLANNING",

	// ── Dynamic Template Drafts & Responses ─────────────────────────
	TEMPLATE_DRAFT_CREATED: "TEMPLATE_DRAFT_CREATED",
	TEMPLATE_DRAFT_UPDATED: "TEMPLATE_DRAFT_UPDATED",
	TEMPLATE_DRAFT_APPROVED: "TEMPLATE_DRAFT_APPROVED",
	TEMPLATE_DRAFT_REJECTED: "TEMPLATE_DRAFT_REJECTED",
	TEMPLATE_DRAFT_CONVERTED: "TEMPLATE_DRAFT_CONVERTED",
	TEMPLATE_DRAFT_DELETED: "TEMPLATE_DRAFT_DELETED",
	TEMPLATE_DRAFT_SUBMITTED_FOR_REVIEW: "TEMPLATE_DRAFT_SUBMITTED_FOR_REVIEW",
	TEMPLATE_RESPONSE_CREATED: "TEMPLATE_RESPONSE_CREATED",
	TEMPLATE_RESPONSE_UPDATED: "TEMPLATE_RESPONSE_UPDATED",
	TEMPLATE_RESPONSE_SUBMITTED: "TEMPLATE_RESPONSE_SUBMITTED",
	TEMPLATE_RESPONSE_VALIDATED: "TEMPLATE_RESPONSE_VALIDATED",
	TEMPLATE_RESPONSE_REJECTED: "TEMPLATE_RESPONSE_REJECTED",
	TEMPLATE_RESPONSE_DELETED: "TEMPLATE_RESPONSE_DELETED",

	// ── Administration & Integrations ────────────────────────────────
	SYSTEM_FEATURE_FLAG_UPDATED: "SYSTEM_FEATURE_FLAG_UPDATED",
	SYSTEM_SETTINGS_UPDATED: "SYSTEM_SETTINGS_UPDATED",
	DIAN_CONFIGURATION_UPDATED: "DIAN_CONFIGURATION_UPDATED",
	PASSKEY_REGISTERED: "PASSKEY_REGISTERED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
