export const APP_ROUTES = {
	home: "/",
	login: "/login",
	register: "/register",
	forgotPassword: "/forgot-password",
	resetPassword: "/reset-password",
	unauthorized: "/unauthorized",
	dashboard: "/dashboard",
	profile: "/profile",
	workRequests: "/work-requests",
	workRequestNew: "/work-requests/new",
	siteVisits: "/site-visits",
	siteVisitNew: "/site-visits/new",
	proposals: "/proposals",
	proposalNew: "/proposals/new",
	purchaseOrders: "/purchase-orders",
	orders: "/orders",
	orderNew: "/orders/new",
	orderKanban: "/orders/kanban",
	planning: "/planning",
	execution: "/execution",
	evidences: "/evidences",
	reports: "/reports",
	deliveryRecords: "/delivery-records",
	billing: "/billing",
	billingSes: "/billing/ses",
	billingInvoices: "/billing/invoices",
	payments: "/payments",
	costs: "/costs",
	assets: "/assets",
	maintenance: "/maintenance",
	documents: "/documents",
	resources: "/resources",
	resourceKits: "/resources/kits",
	templates: "/templates",
	admin: "/admin",
	adminUsers: "/admin/users",
	adminUsersNew: "/admin/users/new",
	adminCustomFields: "/admin/custom-fields",
	settings: "/settings",
	serviceCases: "/service-cases",
	customers: "/customers",
	customerNew: "/customers/new",
	notifications: "/notifications",
} as const;

export type AppRouteKey = keyof typeof APP_ROUTES;
export type AppRoute = (typeof APP_ROUTES)[AppRouteKey];
